/**
 * Centralized TRAINO localization dictionary — the ONLY place user-facing
 * copy for the language-aware screens lives, per spec ("use t('key'), do
 * not scatter translation logic"). Every key must exist in both locales;
 * `translations.test.ts` enforces that no key silently falls back to the
 * wrong language.
 *
 * Scope (spec-honest): this covers the fresh-user journey and the screens
 * an athlete sees most often — Language, Welcome, the assessment flow's
 * structural chrome (headers/CTAs), Review, Plan-ready, the Plan (full
 * week) screen, Home's headline strings, and bottom navigation. Deeper
 * screens (AI Coach reply bodies, Weekly Report prose, per-option data
 * labels such as equipment/allergy names) remain English-only for now —
 * see the final report's "remaining technical debt" for the explicit list.
 */

export type Locale = 'en' | 'ar';

export const LOCALES: { id: Locale; nativeName: string; dir: 'ltr' | 'rtl' }[] = [
  { id: 'en', nativeName: 'English', dir: 'ltr' },
  { id: 'ar', nativeName: 'العربية', dir: 'rtl' },
];

const en = {
  'language.title': 'Choose Your Language',
  'language.subtitle': 'You can change this later in Profile.',
  'language.continue': 'CONTINUE',

  'welcome.headline': 'Build Your Personal Plan',
  'welcome.body':
    "Tell TRAINO about yourself, your sport, your goals, training, equipment, health and nutrition. We'll build a plan around you.",
  'welcome.point.assessment': 'A deep assessment — not a generic quiz',
  'welcome.point.engine': 'A plan generated by TRAINO, not picked from a list',
  'welcome.point.everything': 'Training and nutrition, built together',
  'welcome.cta': 'CREATE MY PLAN',

  'onboarding.next': 'NEXT',
  'onboarding.back': 'BACK',
  'onboarding.step': 'Step {current} of {total}',

  'assessment.about.title': 'About You',
  'assessment.sport.title': 'Your Sport',
  'assessment.location.title': 'Location',
  'assessment.equipment.title': 'Equipment',
  'assessment.experience.title': 'Training',
  'assessment.health.title': 'Health & Injuries',
  'assessment.body.title': 'Measurements',
  'assessment.nutrition.title': 'Nutrition',
  'assessment.review.title': 'Review',

  'review.heading': 'Your Profile',
  'review.subtitle': "TRAINO now has enough information to build your plan.",
  'review.sport': 'Sport',
  'review.position': 'Position / Discipline',
  'review.goal': 'Goal',
  'review.experience': 'Experience',
  'review.trainingDays': 'Training days / week',
  'review.sessionDuration': 'Session duration',
  'review.location': 'Location',
  'review.equipment': 'Equipment',
  'review.priority': 'Performance priority',
  'review.competitiveLevel': 'Competitive level',
  'review.matchesPerWeek': 'Matches / week',
  'review.health': 'Health / limitations',
  'review.nutritionGoal': 'Nutrition goal',
  'review.mealsPerDay': 'Meals / day',
  'review.cta': 'BUILD MY PLAN',
  'review.edit': 'Edit',

  'planReady.building': 'BUILDING YOUR PERSONALIZED PLAN…',
  'planReady.ready': 'YOUR PLAN IS READY',
  'planReady.cta': 'VIEW MY PLAN',

  'plan.title': 'Your Personal Plan',
  'plan.week': 'Week {week}',
  'plan.today': 'TODAY',
  'plan.completed': 'Completed',
  'plan.rest': 'Rest',
  'plan.startWorkout': "START TODAY'S WORKOUT",
  'plan.viewWorkout': 'VIEW WORKOUT',

  'nav.home': 'Home',
  'nav.plan': 'Plan',
  'nav.nutrition': 'Nutrition',
  'nav.progress': 'Progress',
  'nav.profile': 'Profile',
  'nav.aiCoach': 'AI Coach',

  'home.greeting': 'Good morning,',
  'home.todaysPlan': "Today's Plan",
  'home.startWorkout': 'START WORKOUT',
} as const;

export type TranslationKey = keyof typeof en;

const ar: Record<TranslationKey, string> = {
  'language.title': 'اختر لغتك',
  'language.subtitle': 'يمكنك تغيير هذا لاحقًا من الملف الشخصي.',
  'language.continue': 'متابعة',

  'welcome.headline': 'ابنِ خطتك الشخصية',
  'welcome.body':
    'أخبر TRAINO عن نفسك، رياضتك، أهدافك، تدريبك، معداتك، صحتك وتغذيتك. سنبني خطة مصممة خصيصًا لك.',
  'welcome.point.assessment': 'تقييم شامل — وليس اختبارًا عامًا',
  'welcome.point.engine': 'خطة تولدها TRAINO، وليست مختارة من قائمة',
  'welcome.point.everything': 'التدريب والتغذية، مبنيان معًا',
  'welcome.cta': 'أنشئ خطتي',

  'onboarding.next': 'التالي',
  'onboarding.back': 'رجوع',
  'onboarding.step': 'الخطوة {current} من {total}',

  'assessment.about.title': 'عنك',
  'assessment.sport.title': 'رياضتك',
  'assessment.location.title': 'مكان التدريب',
  'assessment.equipment.title': 'المعدات',
  'assessment.experience.title': 'التدريب',
  'assessment.health.title': 'الصحة والإصابات',
  'assessment.body.title': 'القياسات',
  'assessment.nutrition.title': 'التغذية',
  'assessment.review.title': 'المراجعة',

  'review.heading': 'ملفك الشخصي',
  'review.subtitle': 'لدى TRAINO الآن معلومات كافية لبناء خطتك.',
  'review.sport': 'الرياضة',
  'review.position': 'المركز / التخصص',
  'review.goal': 'الهدف',
  'review.experience': 'الخبرة',
  'review.trainingDays': 'أيام التدريب / أسبوع',
  'review.sessionDuration': 'مدة الجلسة',
  'review.location': 'المكان',
  'review.equipment': 'المعدات',
  'review.priority': 'أولوية الأداء',
  'review.competitiveLevel': 'المستوى التنافسي',
  'review.matchesPerWeek': 'المباريات / أسبوع',
  'review.health': 'الصحة / القيود',
  'review.nutritionGoal': 'هدف التغذية',
  'review.mealsPerDay': 'الوجبات / يوم',
  'review.cta': 'ابنِ خطتي',
  'review.edit': 'تعديل',

  'planReady.building': 'جارٍ بناء خطتك الشخصية…',
  'planReady.ready': 'خطتك جاهزة',
  'planReady.cta': 'عرض خطتي',

  'plan.title': 'خطتك الشخصية',
  'plan.week': 'الأسبوع {week}',
  'plan.today': 'اليوم',
  'plan.completed': 'مكتمل',
  'plan.rest': 'راحة',
  'plan.startWorkout': 'ابدأ تمرين اليوم',
  'plan.viewWorkout': 'عرض التمرين',

  'nav.home': 'الرئيسية',
  'nav.plan': 'الخطة',
  'nav.nutrition': 'التغذية',
  'nav.progress': 'التقدم',
  'nav.profile': 'الملف الشخصي',
  'nav.aiCoach': 'المدرب الذكي',

  'home.greeting': 'صباح الخير،',
  'home.todaysPlan': 'خطة اليوم',
  'home.startWorkout': 'ابدأ التمرين',
};

export const TRANSLATIONS: Record<Locale, Record<TranslationKey, string>> = { en, ar };

/** Simple `{placeholder}` interpolation — no external i18n library (spec §45: no
 * unnecessary dependencies). Missing vars are left as literal `{name}` rather than
 * throwing, so a forgotten var is visibly wrong instead of silently crashing a screen. */
export function formatTranslation(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (match, key) => (key in vars ? String(vars[key]) : match));
}
