import type { SportModuleData, WorkoutDayTemplate } from '../../engine/types';

/**
 * Football (soccer) training program — pilot sport for the Deterministic
 * Coaching Engine. Static, pre-authored data: three fixed weekly cycles
 * (one per fitness level), each a fixed list of day templates. The plan
 * engine picks a day from here by index; nothing here is generated live.
 *
 * This is a first-pass, sport-science-informed ruleset meant to prove the
 * architecture end-to-end — treat exact sets/reps/exercise choices as a
 * starting point for a coaching-qualified reviewer to refine, not a
 * clinically-final program.
 */

const beginnerDays: WorkoutDayTemplate[] = [
  {
    id: 'football_beg_speed_lower',
    name: 'Speed + Lower Body',
    focus: 'Football Performance',
    intensity: 'Low',
    durationMin: 35,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '8 min', equipment: [], category: 'warmup' },
      {
        name: 'Bodyweight Squat',
        sets: 3,
        reps: '10',
        equipment: [],
        category: 'strength',
      },
      {
        name: 'Glute Bridge',
        sets: 3,
        reps: '12',
        restSec: 60,
        equipment: [],
        category: 'strength',
      },
      {
        name: 'Walking Lunges',
        sets: 2,
        reps: '8 / leg',
        restSec: 60,
        equipment: [],
        category: 'strength',
      },
      {
        name: 'Step-Ups',
        sets: 2,
        reps: '10 / leg',
        restSec: 60,
        equipment: ['bench'],
        bodyweightAlternative: { name: 'Reverse Lunges', reps: '10 / leg' },
        category: 'strength',
      },
      {
        name: 'Light Sprint Intervals',
        sets: 4,
        reps: '15 sec',
        restSec: 90,
        equipment: [],
        bodyweightAlternative: { name: 'Brisk Walk Intervals (low-impact)', reps: '15 sec' },
        category: 'conditioning',
        highImpact: true,
        contraindications: ['ankle'],
      },
    ],
  },
  {
    id: 'football_beg_upper_core',
    name: 'Upper Body + Core',
    focus: 'Football Performance',
    intensity: 'Low',
    durationMin: 30,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '6 min', equipment: [], category: 'warmup' },
      {
        name: 'Push-Ups',
        sets: 3,
        reps: '8',
        restSec: 60,
        equipment: [],
        category: 'strength',
      },
      {
        name: 'Dumbbell Row',
        sets: 3,
        reps: '10 / side',
        restSec: 60,
        equipment: ['dumbbells'],
        bodyweightAlternative: { name: 'Inverted Row (table)', reps: '8' },
        category: 'strength',
      },
      {
        name: 'Plank',
        sets: 3,
        reps: '30 sec',
        restSec: 45,
        equipment: [],
        category: 'strength',
      },
      {
        name: 'Dead Bug',
        sets: 2,
        reps: '10 / side',
        restSec: 45,
        equipment: [],
        category: 'strength',
      },
    ],
  },
  {
    id: 'football_beg_agility',
    name: 'Agility + Conditioning',
    focus: 'Football Performance',
    intensity: 'Medium',
    durationMin: 35,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '8 min', equipment: [], category: 'warmup' },
      {
        name: 'Ladder Drills (or cone shuffles)',
        sets: 4,
        reps: '20 sec',
        restSec: 40,
        equipment: [],
        bodyweightAlternative: { name: 'Marching Drill (low-impact)', reps: '20 sec' },
        category: 'power',
        highImpact: true,
        contraindications: ['ankle'],
      },
      {
        name: 'Lateral Bounds',
        sets: 3,
        reps: '8 / side',
        restSec: 60,
        equipment: [],
        bodyweightAlternative: { name: 'Lateral Step-Overs (low-impact)', reps: '8 / side' },
        category: 'power',
        highImpact: true,
        contraindications: ['knee', 'ankle'],
      },
      {
        name: 'Shuttle Runs',
        sets: 4,
        reps: '20 sec',
        restSec: 60,
        equipment: [],
        bodyweightAlternative: { name: 'Brisk Walk Intervals (low-impact)', reps: '20 sec' },
        category: 'conditioning',
        highImpact: true,
        contraindications: ['ankle'],
      },
      { name: 'Cool Down', sets: 1, reps: '5 min', equipment: [], category: 'cooldown' },
    ],
  },
];

const intermediateDays: WorkoutDayTemplate[] = [
  {
    id: 'football_int_speed_lower',
    name: 'Speed + Lower Body',
    focus: 'Football Performance',
    intensity: 'Medium',
    durationMin: 45,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '8 min', equipment: [], category: 'warmup' },
      {
        name: 'Back Squat',
        sets: 4,
        reps: '6',
        equipment: ['barbell', 'squat_rack'],
        bodyweightAlternative: { name: 'Bulgarian Split Squat', reps: '10 / leg' },
        category: 'strength',
        contraindications: ['knee'],
      },
      {
        name: 'Romanian Deadlift',
        sets: 3,
        reps: '8',
        restSec: 90,
        equipment: ['barbell'],
        bodyweightAlternative: { name: 'Single-Leg Glute Bridge', reps: '12 / leg' },
        category: 'strength',
        contraindications: ['lower_back'],
      },
      {
        name: 'Bulgarian Split Squat',
        sets: 3,
        reps: '8 / leg',
        restSec: 90,
        equipment: ['bench', 'dumbbells'],
        bodyweightAlternative: { name: 'Bulgarian Split Squat (bodyweight)', reps: '10 / leg' },
        category: 'strength',
        contraindications: ['knee'],
      },
      {
        name: 'Leg Press',
        sets: 3,
        reps: '10',
        restSec: 90,
        equipment: ['cable_machine'],
        bodyweightAlternative: { name: 'Walking Lunges', reps: '12 / leg' },
        category: 'strength',
        contraindications: ['knee'],
      },
      {
        name: 'Sprint Intervals',
        sets: 6,
        reps: '20 sec',
        restSec: 60,
        equipment: [],
        bodyweightAlternative: { name: 'Brisk Walk Intervals (low-impact)', reps: '20 sec' },
        category: 'conditioning',
        highImpact: true,
        contraindications: ['ankle'],
      },
    ],
  },
  {
    id: 'football_int_upper_core',
    name: 'Upper Body + Core',
    focus: 'Football Performance',
    intensity: 'Medium',
    durationMin: 40,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '8 min', equipment: [], category: 'warmup' },
      {
        name: 'Bench Press',
        sets: 4,
        reps: '8',
        equipment: ['barbell', 'bench'],
        bodyweightAlternative: { name: 'Push-Ups', reps: '15' },
        category: 'strength',
        contraindications: ['shoulder'],
      },
      {
        name: 'Pull-Up',
        sets: 3,
        reps: '6-8',
        restSec: 90,
        equipment: ['pull_up_bar'],
        bodyweightAlternative: { name: 'Dumbbell Row', reps: '10 / side' },
        category: 'strength',
        contraindications: ['shoulder'],
      },
      {
        name: 'Cable Rotation',
        sets: 3,
        reps: '10 / side',
        restSec: 60,
        equipment: ['cable_machine'],
        bodyweightAlternative: { name: 'Russian Twist', reps: '16 total' },
        category: 'strength',
      },
      {
        name: 'Hanging Knee Raise',
        sets: 3,
        reps: '10',
        restSec: 60,
        equipment: ['pull_up_bar'],
        bodyweightAlternative: { name: 'Plank', reps: '45 sec' },
        category: 'strength',
      },
      { name: 'Cool Down', sets: 1, reps: '5 min', equipment: [], category: 'cooldown' },
    ],
  },
  {
    id: 'football_int_agility',
    name: 'Agility + Conditioning',
    focus: 'Football Performance',
    intensity: 'High',
    durationMin: 45,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '8 min', equipment: [], category: 'warmup' },
      {
        name: 'Box Jump',
        sets: 4,
        reps: '6',
        restSec: 90,
        equipment: ['plyo_box'],
        bodyweightAlternative: { name: 'Broad Jump', reps: '6' },
        category: 'power',
        highImpact: true,
        contraindications: ['knee', 'ankle'],
      },
      {
        name: 'Ladder Drills',
        sets: 5,
        reps: '20 sec',
        restSec: 40,
        equipment: [],
        bodyweightAlternative: { name: 'Marching Drill (low-impact)', reps: '20 sec' },
        category: 'power',
        highImpact: true,
        contraindications: ['ankle'],
      },
      {
        name: 'Change-of-Direction Sprints',
        sets: 6,
        reps: '15 sec',
        restSec: 60,
        equipment: [],
        bodyweightAlternative: { name: 'Brisk Walk Intervals (low-impact)', reps: '15 sec' },
        category: 'conditioning',
        highImpact: true,
        contraindications: ['ankle', 'knee'],
      },
      {
        name: 'Shuttle Runs',
        sets: 5,
        reps: '25 sec',
        restSec: 45,
        equipment: [],
        bodyweightAlternative: { name: 'Brisk Walk Intervals (low-impact)', reps: '25 sec' },
        category: 'conditioning',
        highImpact: true,
        contraindications: ['ankle'],
      },
      { name: 'Cool Down', sets: 1, reps: '5 min', equipment: [], category: 'cooldown' },
    ],
  },
];

const advancedDays: WorkoutDayTemplate[] = [
  {
    id: 'football_adv_speed_lower',
    name: 'Speed + Lower Body',
    focus: 'Football Performance',
    intensity: 'High',
    durationMin: 55,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '10 min', equipment: [], category: 'warmup' },
      {
        name: 'Back Squat',
        sets: 5,
        reps: '4',
        restSec: 120,
        equipment: ['barbell', 'squat_rack'],
        bodyweightAlternative: { name: 'Pistol Squat Progression', reps: '6 / leg' },
        category: 'strength',
        contraindications: ['knee'],
      },
      {
        name: 'Trap Bar Deadlift',
        sets: 4,
        reps: '5',
        restSec: 120,
        equipment: ['barbell'],
        bodyweightAlternative: { name: 'Single-Leg RDL', reps: '10 / leg' },
        category: 'strength',
        contraindications: ['lower_back'],
      },
      {
        name: 'Bulgarian Split Squat (loaded)',
        sets: 4,
        reps: '6 / leg',
        restSec: 90,
        equipment: ['bench', 'dumbbells'],
        bodyweightAlternative: { name: 'Jump Split Squat', reps: '8 / leg' },
        category: 'strength',
        contraindications: ['knee'],
      },
      {
        name: 'Nordic Hamstring Curl',
        sets: 3,
        reps: '6',
        restSec: 90,
        equipment: [],
        bodyweightAlternative: { name: 'Glute Bridge Hold', reps: '30 sec' },
        category: 'strength',
        contraindications: ['knee'],
      },
      {
        name: 'Max Velocity Sprints',
        sets: 8,
        reps: '20 sec',
        restSec: 90,
        equipment: [],
        bodyweightAlternative: { name: 'Brisk Walk Intervals (low-impact)', reps: '20 sec' },
        category: 'conditioning',
        highImpact: true,
        contraindications: ['ankle'],
      },
    ],
  },
  {
    id: 'football_adv_upper_core',
    name: 'Upper Body + Core',
    focus: 'Football Performance',
    intensity: 'Medium',
    durationMin: 45,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '8 min', equipment: [], category: 'warmup' },
      {
        name: 'Weighted Pull-Up',
        sets: 4,
        reps: '6',
        restSec: 120,
        equipment: ['pull_up_bar'],
        bodyweightAlternative: { name: 'Pull-Up', reps: '8-10' },
        category: 'strength',
        contraindications: ['shoulder'],
      },
      {
        name: 'Bench Press',
        sets: 4,
        reps: '6',
        restSec: 120,
        equipment: ['barbell', 'bench'],
        bodyweightAlternative: { name: 'Explosive Push-Ups', reps: '12' },
        category: 'strength',
        contraindications: ['shoulder'],
      },
      {
        name: 'Single-Arm Cable Row',
        sets: 3,
        reps: '10 / side',
        restSec: 75,
        equipment: ['cable_machine'],
        bodyweightAlternative: { name: 'Dumbbell Row', reps: '12 / side' },
        category: 'strength',
      },
      {
        name: 'Pallof Press',
        sets: 3,
        reps: '12 / side',
        restSec: 60,
        equipment: ['cable_machine', 'resistance_bands'],
        bodyweightAlternative: { name: 'Side Plank', reps: '40 sec / side' },
        category: 'strength',
      },
      { name: 'Cool Down', sets: 1, reps: '5 min', equipment: [], category: 'cooldown' },
    ],
  },
  {
    id: 'football_adv_agility',
    name: 'Agility + Conditioning',
    focus: 'Football Performance',
    intensity: 'High',
    durationMin: 50,
    exercises: [
      { name: 'Warm Up', sets: 1, reps: '10 min', equipment: [], category: 'warmup' },
      {
        name: 'Depth Jump',
        sets: 5,
        reps: '5',
        restSec: 120,
        equipment: ['plyo_box'],
        bodyweightAlternative: { name: 'Box Jump', reps: '6' },
        category: 'power',
        highImpact: true,
        contraindications: ['knee', 'ankle'],
      },
      {
        name: 'Reactive Agility Drills',
        sets: 6,
        reps: '20 sec',
        restSec: 45,
        equipment: [],
        bodyweightAlternative: { name: 'Marching Drill (low-impact)', reps: '20 sec' },
        category: 'power',
        highImpact: true,
        contraindications: ['ankle'],
      },
      {
        name: 'Repeated Sprint Ability',
        sets: 8,
        reps: '15 sec',
        restSec: 45,
        equipment: [],
        bodyweightAlternative: { name: 'Brisk Walk Intervals (low-impact)', reps: '15 sec' },
        category: 'conditioning',
        highImpact: true,
        contraindications: ['ankle'],
      },
      {
        name: 'Small-Sided Game Simulation',
        sets: 3,
        reps: '4 min',
        restSec: 90,
        equipment: [],
        category: 'conditioning',
      },
      { name: 'Cool Down', sets: 1, reps: '6 min', equipment: [], category: 'cooldown' },
    ],
  },
];

export const footballModule: SportModuleData = {
  id: 'football',
  program: {
    beginner: beginnerDays,
    intermediate: intermediateDays,
    advanced: advancedDays,
  },
  nutritionProfile: {
    proteinGPerKg: 2.0,
    carbBias: 'high',
  },
};
