import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Screen } from '../components/ui/Screen';
import { StatusBar } from '../components/ui/StatusBar';
import { Icon } from '../components/ui/Icon';
import { useProfile } from '../domain/state/ProfileContext';
import { useLocale } from '../domain/state/LocaleContext';
import { SPORTS } from '../domain/sports/sports';
import { GOAL_OPTIONS } from '../domain/assessment/goals';
import { TRAINING_LOCATIONS } from '../domain/assessment/trainingLocations';
import { PRIORITY_OPTIONS } from '../domain/assessment/experience';

/**
 * Shown once, immediately after Review's "BUILD MY PLAN" (spec §25/§26). The
 * plan itself is already fully generated by this point — `completeAssessment()`
 * already ran on the Review screen, and every engine call is a deterministic,
 * synchronous function of the persisted profile (planEngine.ts / nutritionEngine.ts).
 * The brief "Building..." state is a short, honest UI transition, not a
 * simulated multi-second computation — the plan does not get more "ready"
 * the longer this screen sits.
 */
export default function PlanReady() {
  const navigate = useNavigate();
  const { answers } = useProfile();
  const { t } = useLocale();
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const id = setTimeout(() => setReady(true), 500);
    return () => clearTimeout(id);
  }, []);

  const sportName = SPORTS.find((s) => s.id === answers.sport)?.name ?? answers.sport;
  const goalName = (GOAL_OPTIONS.find((g) => g.id === answers.goal)?.name ?? answers.goal).toLowerCase();
  const locationName = TRAINING_LOCATIONS.find((l) => answers.trainingLocationIds.includes(l.id))?.name?.toLowerCase();
  const priorityName = PRIORITY_OPTIONS.find((p) => p.id === (answers.performancePriority ?? 'strength'))?.name.toLowerCase();
  const days = answers.daysAvailablePerWeek || 3;

  const explanation = [
    `Built around your ${sportName} ${goalName} goal`,
    `${days} available training day${days === 1 ? '' : 's'}`,
    locationName ? `${locationName} access` : null,
    priorityName ? `${priorityName} priority` : null,
  ]
    .filter(Boolean)
    .join(', ') + '.';

  return (
    <Screen withNav={false} className="flex flex-col">
      <StatusBar />
      <div className="flex-1 flex flex-col items-center justify-center px-6 text-center">
        <div className={`text-red drop-shadow-[0_0_20px_rgba(224,39,46,0.5)] mb-6 ${ready ? '' : 'animate-pulse'}`}>
          <Icon name={ready ? 'checkPlain' : 'aiMascot'} size={ready ? 56 : 84} strokeWidth={ready ? 2.6 : 1.4} />
        </div>
        <h1 className="text-white text-[22px] font-extrabold leading-tight">
          {ready ? t('planReady.ready') : t('planReady.building')}
        </h1>
        {ready && (
          <p className="text-text-secondary text-[13.5px] leading-relaxed mt-3 max-w-[300px]">{explanation}</p>
        )}
      </div>
      {ready && (
        <div className="px-5 pb-8">
          <button
            onClick={() => navigate('/plan', { replace: true })}
            className="w-full bg-red rounded-button py-4 text-white font-extrabold text-[15px] tracking-wide shadow-button"
          >
            {t('planReady.cta')}
          </button>
        </div>
      )}
    </Screen>
  );
}
