import type { MealTemplate } from '../engine/types';

/**
 * Static meal template library — the nutrition engine only ever selects
 * and filters from this pre-authored list; it never generates a meal.
 */
export const MEAL_LIBRARY: MealTemplate[] = [
  // Breakfast
  {
    id: 'bf_oatmeal_whey',
    name: 'Oatmeal, Banana & Whey Protein',
    description: 'Oatmeal, Banana, Whey Protein',
    slot: 'breakfast',
    kcal: 450,
    proteinG: 30,
    carbsG: 55,
    fatG: 10,
    dietaryTags: ['no_restriction', 'high_protein'],
    allergens: ['dairy'],
    budgetTier: 'low',
  },
  {
    id: 'bf_tofu_scramble',
    name: 'Tofu Scramble with Avocado',
    description: 'Vegan tofu scramble, avocado, whole-grain toast',
    slot: 'breakfast',
    kcal: 420,
    proteinG: 24,
    carbsG: 30,
    fatG: 22,
    dietaryTags: ['no_restriction', 'vegetarian', 'vegan'],
    allergens: [],
    budgetTier: 'medium',
  },
  {
    id: 'bf_greek_yogurt',
    name: 'Greek Yogurt Parfait',
    description: 'Greek yogurt, berries, mixed nuts',
    slot: 'breakfast',
    kcal: 380,
    proteinG: 26,
    carbsG: 40,
    fatG: 12,
    dietaryTags: ['no_restriction', 'vegetarian', 'high_protein'],
    allergens: ['dairy', 'nuts'],
    budgetTier: 'low',
  },
  {
    id: 'bf_egg_white_omelet',
    name: 'Egg White Omelet',
    description: 'Egg whites, spinach, feta',
    slot: 'breakfast',
    kcal: 350,
    proteinG: 32,
    carbsG: 10,
    fatG: 16,
    dietaryTags: ['no_restriction', 'vegetarian', 'high_protein', 'low_carb'],
    allergens: ['dairy', 'eggs'],
    budgetTier: 'medium',
  },
  {
    id: 'bf_salmon_bagel',
    name: 'Smoked Salmon Bagel',
    description: 'Smoked salmon, cream cheese, bagel',
    slot: 'breakfast',
    kcal: 480,
    proteinG: 28,
    carbsG: 50,
    fatG: 16,
    dietaryTags: ['no_restriction'],
    allergens: ['gluten', 'dairy'],
    budgetTier: 'high',
  },

  // Lunch
  {
    id: 'ln_chicken_rice',
    name: 'Chicken, Rice & Vegetables',
    description: 'Chicken, Rice, Vegetables',
    slot: 'lunch',
    kcal: 620,
    proteinG: 45,
    carbsG: 65,
    fatG: 14,
    dietaryTags: ['no_restriction', 'high_protein'],
    allergens: [],
    budgetTier: 'low',
  },
  {
    id: 'ln_lentil_curry',
    name: 'Lentil & Vegetable Curry',
    description: 'Lentil curry with rice',
    slot: 'lunch',
    kcal: 580,
    proteinG: 24,
    carbsG: 80,
    fatG: 12,
    dietaryTags: ['no_restriction', 'vegetarian', 'vegan'],
    allergens: [],
    budgetTier: 'low',
  },
  {
    id: 'ln_salmon_quinoa',
    name: 'Grilled Salmon with Quinoa',
    description: 'Grilled salmon, quinoa, greens',
    slot: 'lunch',
    kcal: 600,
    proteinG: 40,
    carbsG: 45,
    fatG: 22,
    dietaryTags: ['no_restriction', 'high_protein', 'low_carb'],
    allergens: [],
    budgetTier: 'high',
  },
  {
    id: 'ln_turkey_wrap',
    name: 'Turkey & Avocado Wrap',
    description: 'Turkey, avocado, whole-wheat wrap',
    slot: 'lunch',
    kcal: 550,
    proteinG: 35,
    carbsG: 50,
    fatG: 18,
    dietaryTags: ['no_restriction'],
    allergens: ['gluten'],
    budgetTier: 'medium',
  },
  {
    id: 'ln_chickpea_salad',
    name: 'Chickpea & Feta Salad',
    description: 'Chickpeas, feta, mixed greens',
    slot: 'lunch',
    kcal: 520,
    proteinG: 22,
    carbsG: 55,
    fatG: 18,
    dietaryTags: ['no_restriction', 'vegetarian'],
    allergens: ['dairy'],
    budgetTier: 'medium',
  },

  // Snack
  {
    id: 'sn_yogurt_nuts',
    name: 'Greek Yogurt & Nuts',
    description: 'Greek Yogurt, Nuts',
    slot: 'snack',
    kcal: 300,
    proteinG: 18,
    carbsG: 20,
    fatG: 15,
    dietaryTags: ['no_restriction', 'vegetarian', 'high_protein'],
    allergens: ['dairy', 'nuts'],
    budgetTier: 'low',
  },
  {
    id: 'sn_protein_shake',
    name: 'Protein Shake & Banana',
    description: 'Whey protein shake, banana',
    slot: 'snack',
    kcal: 280,
    proteinG: 25,
    carbsG: 30,
    fatG: 5,
    dietaryTags: ['no_restriction', 'high_protein'],
    allergens: ['dairy'],
    budgetTier: 'low',
  },
  {
    id: 'sn_hummus_veggies',
    name: 'Hummus & Veggie Sticks',
    description: 'Hummus with carrot and cucumber sticks',
    slot: 'snack',
    kcal: 250,
    proteinG: 8,
    carbsG: 28,
    fatG: 12,
    dietaryTags: ['no_restriction', 'vegetarian', 'vegan'],
    allergens: [],
    budgetTier: 'low',
  },
  {
    id: 'sn_mixed_nuts',
    name: 'Mixed Nuts & Dried Fruit',
    description: 'Mixed nuts and dried fruit',
    slot: 'snack',
    kcal: 320,
    proteinG: 10,
    carbsG: 25,
    fatG: 20,
    dietaryTags: ['no_restriction', 'vegetarian', 'vegan'],
    allergens: ['nuts'],
    budgetTier: 'medium',
  },
  {
    id: 'sn_cottage_pineapple',
    name: 'Cottage Cheese & Pineapple',
    description: 'Cottage cheese with pineapple',
    slot: 'snack',
    kcal: 260,
    proteinG: 22,
    carbsG: 22,
    fatG: 6,
    dietaryTags: ['no_restriction', 'vegetarian', 'high_protein', 'low_carb'],
    allergens: ['dairy'],
    budgetTier: 'low',
  },

  // Dinner
  {
    id: 'dn_salmon_potatoes',
    name: 'Salmon, Potatoes & Salad',
    description: 'Salmon, Potatoes, Salad',
    slot: 'dinner',
    kcal: 610,
    proteinG: 38,
    carbsG: 45,
    fatG: 26,
    dietaryTags: ['no_restriction', 'high_protein'],
    allergens: [],
    budgetTier: 'high',
  },
  {
    id: 'dn_chicken_veg',
    name: 'Grilled Chicken with Vegetables',
    description: 'Grilled chicken breast, steamed vegetables',
    slot: 'dinner',
    kcal: 520,
    proteinG: 48,
    carbsG: 30,
    fatG: 16,
    dietaryTags: ['no_restriction', 'high_protein', 'low_carb'],
    allergens: [],
    budgetTier: 'medium',
  },
  {
    id: 'dn_tofu_stirfry',
    name: 'Tofu & Vegetable Stir-Fry',
    description: 'Vegan tofu and vegetable stir-fry',
    slot: 'dinner',
    kcal: 480,
    proteinG: 26,
    carbsG: 50,
    fatG: 16,
    dietaryTags: ['no_restriction', 'vegetarian', 'vegan'],
    allergens: [],
    budgetTier: 'low',
  },
  {
    id: 'dn_steak_sweet_potato',
    name: 'Beef Steak with Sweet Potato',
    description: 'Beef steak, roasted sweet potato',
    slot: 'dinner',
    kcal: 650,
    proteinG: 42,
    carbsG: 45,
    fatG: 28,
    dietaryTags: ['no_restriction'],
    allergens: [],
    budgetTier: 'high',
  },
  {
    id: 'dn_shrimp_stirfry',
    name: 'Shrimp & Vegetable Stir-Fry',
    description: 'Shrimp, mixed vegetables, low-carb sauce',
    slot: 'dinner',
    kcal: 500,
    proteinG: 35,
    carbsG: 40,
    fatG: 18,
    dietaryTags: ['no_restriction', 'low_carb'],
    allergens: ['shellfish'],
    budgetTier: 'high',
  },
];
